/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pratikum17062025;

/**
 *
 * @author user
 */
public class MenuMinuman extends javax.swing.JFrame {

    private MenuUtama utama;
    /**
     * Creates new form MenuMinuman
     */
    public MenuMinuman() {
        initComponents();
    }
    public MenuMinuman(MenuUtama utama){
        this.utama = utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkNasgor = new javax.swing.JCheckBox();
        cbNutri = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbTeh = new javax.swing.JComboBox<>();
        txtTotNutri = new javax.swing.JTextField();
        txtTotTeh = new javax.swing.JTextField();
        chkSoto = new javax.swing.JCheckBox();
        chkMigor = new javax.swing.JCheckBox();
        txtNutri = new javax.swing.JTextField();
        cbAlpukat = new javax.swing.JComboBox<>();
        btnTot = new javax.swing.JButton();
        txtTeh = new javax.swing.JTextField();
        txtTotAlpukat = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtAlpukat = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        txtTotApel = new javax.swing.JTextField();
        cbApel = new javax.swing.JComboBox<>();
        txtApel = new javax.swing.JTextField();
        chkSate = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chkNasgor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkNasgor.setText("Teh es");
        chkNasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNasgorActionPerformed(evt);
            }
        });

        cbNutri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbNutri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbNutri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNutriActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("MENU MINUMAN");

        cbTeh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbTeh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTehActionPerformed(evt);
            }
        });

        txtTotNutri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotNutri.setText("0");

        txtTotTeh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotTeh.setText("0");
        txtTotTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotTehActionPerformed(evt);
            }
        });

        chkSoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkSoto.setText("Nutrisari");
        chkSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSotoActionPerformed(evt);
            }
        });

        chkMigor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkMigor.setText("Jus Alpukat");
        chkMigor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMigorActionPerformed(evt);
            }
        });

        txtNutri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNutri.setText("0");
        txtNutri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNutriActionPerformed(evt);
            }
        });

        cbAlpukat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbAlpukat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbAlpukat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlpukatActionPerformed(evt);
            }
        });

        btnTot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTot.setText("Total");
        btnTot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotActionPerformed(evt);
            }
        });

        txtTeh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTeh.setText("0");
        txtTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTehActionPerformed(evt);
            }
        });

        txtTotAlpukat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotAlpukat.setText("0");
        txtTotAlpukat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotAlpukatActionPerformed(evt);
            }
        });

        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotal.setText("0");

        txtAlpukat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAlpukat.setText("0");
        txtAlpukat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlpukatActionPerformed(evt);
            }
        });

        btnKembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKembali.setText("Kembali ke Menu Utama");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        txtTotApel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotApel.setText("0");

        cbApel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbApel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbApel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbApelActionPerformed(evt);
            }
        });

        txtApel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtApel.setText("0");
        txtApel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApelActionPerformed(evt);
            }
        });

        chkSate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkSate.setText("STMJ");
        chkSate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkSoto)
                                    .addComponent(chkMigor)
                                    .addComponent(chkSate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtApel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(80, 80, 80)
                                        .addComponent(cbApel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(txtTotApel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtAlpukat, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(80, 80, 80)
                                        .addComponent(cbAlpukat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(txtTotAlpukat, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNutri, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(80, 80, 80)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnTot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbNutri, 0, 98, Short.MAX_VALUE))
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTotNutri, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnKembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(chkNasgor)
                                .addGap(90, 90, 90)
                                .addComponent(txtTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(cbTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(txtTotTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkNasgor)
                    .addComponent(txtTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkMigor)
                        .addGap(49, 49, 49)
                        .addComponent(chkSate))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlpukat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAlpukat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotAlpukat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbApel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotApel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSoto)
                    .addComponent(txtNutri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNutri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotNutri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTot))
                .addGap(39, 39, 39)
                .addComponent(btnKembali)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNasgorActionPerformed
        txtTeh.setText("10000");

    }//GEN-LAST:event_chkNasgorActionPerformed

    private void cbNutriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNutriActionPerformed
        int jml = (int)cbNutri.getSelectedIndex();
        double harga = Double.parseDouble(txtNutri.getText());
        double total = jml * harga;
        txtTotNutri.setText(Double.toString(total));
    }//GEN-LAST:event_cbNutriActionPerformed

    private void cbTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTehActionPerformed
        int jml = (int)cbTeh.getSelectedIndex();
        double harga = Double.parseDouble(txtTeh.getText());
        double total = jml * harga;
        txtTotTeh.setText(Double.toString(total));
    }//GEN-LAST:event_cbTehActionPerformed

    private void txtTotTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotTehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotTehActionPerformed

    private void chkSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSotoActionPerformed
        txtNutri.setText("12000");
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSotoActionPerformed

    private void chkMigorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMigorActionPerformed
        txtAlpukat.setText("15000");
    }//GEN-LAST:event_chkMigorActionPerformed

    private void txtNutriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNutriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNutriActionPerformed

    private void cbAlpukatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlpukatActionPerformed
        int jml = (int)cbAlpukat.getSelectedIndex();
        double harga = Double.parseDouble(txtAlpukat.getText());
        double total = jml * harga;
        txtTotAlpukat.setText(Double.toString(total));
    }//GEN-LAST:event_cbAlpukatActionPerformed

    private void btnTotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotActionPerformed
        double nasgor = Double.parseDouble(txtTotTeh.getText());
        double migor = Double.parseDouble(txtTotAlpukat.getText());
        double sate = Double.parseDouble(txtTotApel.getText());
        double soto = Double.parseDouble(txtTotNutri.getText());

        double total = nasgor + migor + sate + soto;
        txtTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_btnTotActionPerformed

    private void txtTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTehActionPerformed

    }//GEN-LAST:event_txtTehActionPerformed

    private void txtTotAlpukatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotAlpukatActionPerformed

    }//GEN-LAST:event_txtTotAlpukatActionPerformed

    private void txtAlpukatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlpukatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlpukatActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotal.getText();
        utama.SetTotalMinuman(total);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void cbApelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbApelActionPerformed
        int jml = (int)cbApel.getSelectedIndex();
        double harga = Double.parseDouble(txtApel.getText());
        double total = jml * harga;
        txtTotApel.setText(Double.toString(total));
    }//GEN-LAST:event_cbApelActionPerformed

    private void txtApelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApelActionPerformed

    private void chkSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSateActionPerformed
        txtApel.setText("7000");
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTot;
    private javax.swing.JComboBox<String> cbAlpukat;
    private javax.swing.JComboBox<String> cbApel;
    private javax.swing.JComboBox<String> cbNutri;
    private javax.swing.JComboBox<String> cbTeh;
    private javax.swing.JCheckBox chkMigor;
    private javax.swing.JCheckBox chkNasgor;
    private javax.swing.JCheckBox chkSate;
    private javax.swing.JCheckBox chkSoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAlpukat;
    private javax.swing.JTextField txtApel;
    private javax.swing.JTextField txtNutri;
    private javax.swing.JTextField txtTeh;
    private javax.swing.JTextField txtTotAlpukat;
    private javax.swing.JTextField txtTotApel;
    private javax.swing.JTextField txtTotNutri;
    private javax.swing.JTextField txtTotTeh;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
